### ISSUE TITLE
Dead link in setup page

### ISSUE THREAD

**Issue by FranzEricSchneider** [zdelrosario/data-science-curriculum#1]
Hi! Running along at home with a friend, found a dead link. On this page: https://github.com/zdelrosario/data-science-curriculum/blob/master/exercises/e-setup00-install.md

The "download the source" link is dead for me: https://github.com/zdelrosario/data-science-curriculum/blob/master/exercises/e-setup00-install.Rmd

![Screenshot from 2020-07-08 19-10-52](https://user-images.githubusercontent.com/3709527/86979243-d007bf80-c14e-11ea-99e0-d79df35ff5f7.png)

Let me know if you don't want issues raised, figured it could be helpful. No pressure to address them, for example this can be worked around easily with cloning.

**Comment by zdelrosario** [comment]
Thanks Eric! Should be fixed with the latest commit. For clarity I absolutely welcome issues and contributions; so much so that I just added a guide to [Contributing](https://github.com/zdelrosario/data-science-curriculum/blob/master/contributing.md).
