### ISSUE TITLE
Missing solution for e-stat03-descriptive

### ISSUE THREAD

**Issue by jenwei** [zdelrosario/data-science-curriculum#8]
Currently, there are two `task` blocks under the `Observations` section - guessing the second should be a `solution` block?

https://github.com/zdelrosario/data-science-curriculum/blob/e47f4a31ac351d85ebe58677786c38e26a32e840/exercises/e-stat03-descriptive-master.Rmd#L405-L412

**Comment by zdelrosario** [comment]
Fixed with #9
